image: python:2.7

all_tests:
  script:
    - pip install pip
    - pip install -r requirements.txt
  when: on_success
  only:
    - dev

services:
  - postgres:latest

variables:
  POSTGRES_DB: dev
  POSTGRES_USER: dev
  POSTGRES_PASSWORD: dev
