# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 06:57
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0013_auto_20180610_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashdesk',
            options={'verbose_name': 'Cash Desk', 'verbose_name_plural': 'Cash Desks'},
        ),
        migrations.AlterField(
            model_name='cashdesk',
            name='owners',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(b'0', b'trotto'), (b'1', b'foo')], max_length=3, verbose_name=b'Owners'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cashdeskowner',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(b'1', b"Comunita' Tossicodipendenti"), (b'2', b"Comunita' Disabili"), (b'3', b'Centro Diurno Disabili'), (b'4', b'Accoglienza Immigrati'), (b'5', b'Spese Generali')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'Manager'), (2, b'Social Operator'), (3, b'OSS')], null=True),
        ),
    ]
