# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 08:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0015_auto_20180620_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashdesk',
            name='owners',
        ),
    ]
