# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0016_remove_cashdesk_owners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cashdeskowner',
            field=models.ManyToManyField(blank=True, to='settings.CashDesk'),
        ),
    ]
