# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-23 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0017_auto_20180620_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='movementscausal',
            name='admin',
            field=models.BooleanField(default=False, help_text=b'[Select for assign only for admin]', verbose_name=b'Admin Only'),
        ),
    ]
