# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-23 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0018_auto_20180623_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashdesk',
            name='owners',
            field=models.ManyToManyField(blank=True, null=True, to='settings.Profile'),
        ),
        migrations.AlterField(
            model_name='movementscausal',
            name='admin',
            field=models.BooleanField(default=False, help_text=b'[Select for assign only to admins]', verbose_name=b'Admin Only'),
        ),
    ]
