# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-23 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0019_auto_20180623_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashdesk',
            name='owners',
            field=models.ManyToManyField(blank=True, to='settings.Profile'),
        ),
    ]
