# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-23 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0020_auto_20180623_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashdesk',
            name='owners',
        ),
    ]
