# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0021_remove_cashdesk_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='services',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.CashDesk'),
        ),
    ]
