# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0024_auto_20180627_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mv_type', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Movements Types',
            },
        ),
    ]
