# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0025_movementstype'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashdesk',
            name='opening_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name=b'Opening Amount'),
        ),
    ]
