# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0026_cashdesk_opening_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='services',
            field=models.ManyToManyField(blank=True, to='settings.CashDesk'),
        ),
    ]
