# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-11 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0027_customer_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('qualify', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('services', models.ManyToManyField(blank=True, to='settings.CashDesk')),
            ],
            options={
                'verbose_name_plural': 'Operators',
            },
        ),
    ]
