# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-11 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0028_operatornew'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operator',
            options={'verbose_name_plural': 'Operators OLD'},
        ),
    ]
