# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-16 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0029_auto_20180711_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='movementscausal',
            name='in_out',
            field=models.PositiveSmallIntegerField(choices=[(1, b'IN'), (2, b'OUT')], null=True, verbose_name=b'In / Out'),
        ),
    ]
