# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-19 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0030_movementscausal_in_out'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashpaymant', models.CharField(max_length=200, verbose_name=b'Cash Payment')),
            ],
            options={
                'verbose_name': 'Cash Payments',
                'verbose_name_plural': 'Cash Payments',
            },
        ),
        migrations.AddField(
            model_name='movementscausal',
            name='cashpaymant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.CashPayment', verbose_name=b'Cash Payment'),
        ),
    ]
