# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-19 07:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0031_auto_20180719_0923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashpayment',
            old_name='cashpaymant',
            new_name='cashpayment',
        ),
    ]
