# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-24 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0032_auto_20180719_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='services',
        ),
        migrations.DeleteModel(
            name='Operator',
        ),
    ]
