# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-11 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0011_auto_20180610_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaScheduler',
            fields=[
            ],
            options={
                'verbose_name': 'Agenda Planner',
                'proxy': True,
                'verbose_name_plural': 'Agenda Planner',
                'indexes': [],
            },
            bases=('tools.agenda',),
        ),
    ]
