# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-16 07:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0012_agendascheduler'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgendaScheduler',
        ),
        migrations.CreateModel(
            name='Planner',
            fields=[
            ],
            options={
                'verbose_name': 'Agenda',
                'proxy': True,
                'verbose_name_plural': 'Planner',
                'indexes': [],
            },
            bases=('tools.agenda',),
        ),
        migrations.AlterModelOptions(
            name='agenda',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
    ]
