# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 07:38
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0013_auto_20180616_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='text',
            field=tinymce.models.HTMLField(verbose_name=b'Content'),
        ),
    ]
