# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0014_auto_20180618_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='upload',
            field=models.ImageField(null=True, upload_to=b'static/uploads/'),
        ),
    ]
