# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0015_diary_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='upload',
            field=models.ImageField(null=True, upload_to=b'uploads/2018/06/18/'),
        ),
    ]
