# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 14:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tools.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0013_auto_20180610_1100'),
        ('tools', '0017_auto_20180618_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashMovements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annulled', models.BooleanField(default=True, help_text=b'[Deselect for cancel entry]', verbose_name=b'Validation')),
                ('recived', models.BooleanField(default=False, verbose_name=b'Recived')),
                ('operation_date', models.DateField(verbose_name=b'Operation Date')),
                ('document_date', models.DateField(blank=True, null=True, verbose_name=b'Document Date')),
                ('supplier', models.CharField(max_length=200, verbose_name=b'Supplier')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name=b'Amount')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name=b'Note')),
                ('sign', models.CharField(blank=True, max_length=200, verbose_name=b'Sign')),
                ('protocol', models.IntegerField(default=tools.models.protocolgen, editable=False, unique=True)),
                ('author', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL)),
                ('cashdesk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.CashDesk', verbose_name=b'Cash Service')),
                ('causal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.MovementsCausal', verbose_name=b'Causal')),
                ('customer', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.Customer', verbose_name=b'Service Customer')),
            ],
        ),
    ]
