# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0018_cashmovements'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashmovements',
            options={'verbose_name_plural': 'Cash Movements'},
        ),
        migrations.AlterField(
            model_name='diary',
            name='upload',
            field=models.FileField(null=True, upload_to=b'uploads/2018/06/20/'),
        ),
    ]
