# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 13:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0017_auto_20180620_1517'),
        ('tools', '0019_auto_20180620_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashMovementsCustomerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_date', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('supplier', models.CharField(max_length=200, verbose_name=b'Supplier')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name=b'Amount')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name=b'Note')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.Customer', verbose_name=b'Service Customer')),
            ],
        ),
        migrations.AlterField(
            model_name='cashmovements',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cashmovements',
            name='operation_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name=b'Operation Date'),
        ),
        migrations.AlterField(
            model_name='cashmovements',
            name='sign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.Operator', verbose_name=b'Sign'),
        ),
        migrations.AddField(
            model_name='cashmovementscustomerdetails',
            name='prot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.CashMovements'),
        ),
    ]
