# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0020_auto_20180620_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashmovements',
            name='sign',
            field=models.CharField(blank=True, max_length=200, verbose_name=b'Sign'),
        ),
    ]
