# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0022_auto_20180620_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashmovementscustomerdetails',
            name='supplier',
        ),
        migrations.AlterField(
            model_name='cashmovements',
            name='supplier',
            field=models.CharField(max_length=200, null=True, verbose_name=b'Supplier'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='upload',
            field=models.FileField(null=True, upload_to=b'uploads/2018/06/22/'),
        ),
    ]
