# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-23 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0025_auto_20180623_1224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashmovementscustomerdetails',
            options={'verbose_name_plural': 'Cash Movements Customer Details'},
        ),
    ]
