# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-24 13:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0021_remove_cashdesk_owners'),
        ('tools', '0026_auto_20180623_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmaceuticalInventoryMovements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_discharge', models.PositiveSmallIntegerField(blank=True, choices=[(1, b'LOAD'), (2, b'DISCHARGE')], null=True)),
                ('annulled', models.BooleanField(default=True, help_text=b'[Deselect for cancel entry]', verbose_name=b'Validation')),
                ('operation_date', models.DateField(default=django.utils.timezone.now, verbose_name=b'Operation Date')),
                ('drug', models.CharField(blank=True, max_length=200, verbose_name=b'Generic Drug')),
                ('quantity', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=200, verbose_name=b'Note')),
                ('author', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cashdesk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.CashDesk', verbose_name=b'Cash Service')),
                ('customer', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.Customer', verbose_name=b'Service Customer')),
                ('sign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.Operator', verbose_name=b'Sign')),
            ],
            options={
                'verbose_name_plural': 'Pharmaceutical Inventory Movements',
            },
        ),
        migrations.AlterField(
            model_name='diary',
            name='upload',
            field=models.FileField(null=True, upload_to=b'uploads/2018/06/24/'),
        ),
    ]
