# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0027_auto_20180624_1504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planner',
            options={'verbose_name': 'Agenda', 'verbose_name_plural': 'Events Planner'},
        ),
        migrations.AddField(
            model_name='diary',
            name='recurrence',
            field=recurrence.fields.RecurrenceField(null=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='upload',
            field=models.FileField(null=True, upload_to=b'uploads/2018/06/26/'),
        ),
        migrations.AlterField(
            model_name='pharmaceuticalinventorymovements',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.Customer', verbose_name=b'Service Customer'),
        ),
        migrations.AlterField(
            model_name='pharmaceuticalinventorymovements',
            name='load_discharge',
            field=models.PositiveSmallIntegerField(choices=[(1, b'LOAD'), (2, b'UNLOAD')], null=True, verbose_name=b'Load / Discharge'),
        ),
    ]
