# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 07:10
from __future__ import unicode_literals

from django.db import migrations
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0028_auto_20180626_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='recurrence',
        ),
        migrations.AddField(
            model_name='agenda',
            name='recurrence',
            field=recurrence.fields.RecurrenceField(null=True),
        ),
    ]
