# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0029_auto_20180626_0910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pharmaceuticalinventorymovements',
            options={'verbose_name': 'Pharma Inventory', 'verbose_name_plural': 'Pharmaceutical Inventory Movements'},
        ),
        migrations.AlterField(
            model_name='diary',
            name='upload',
            field=models.FileField(null=True, upload_to=b'uploads/2018/06/27/'),
        ),
    ]
