# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0031_cashmovements_mv_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashmovements',
            name='mv_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.MovementsType', verbose_name=b'Type'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='upload',
            field=models.FileField(null=True, upload_to=b'uploads/2018/06/28/'),
        ),
    ]
