# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0032_auto_20180628_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='upload',
            field=models.FileField(null=True, upload_to=b'uploads/2018/07/03/'),
        ),
    ]
