# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-11 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0035_auto_20180711_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashmovements',
            name='sign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.OperatorNew', verbose_name=b'Sign'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='sign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.OperatorNew'),
        ),
        migrations.AlterField(
            model_name='pharmaceuticalinventorymovements',
            name='sign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.OperatorNew', verbose_name=b'Sign'),
        ),
    ]
