# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-12 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0036_auto_20180711_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to=b'uploads/2018/07/12/'),
        ),
        migrations.AlterField(
            model_name='pharmaceuticalinventorymovements',
            name='customer',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'cashdesk', chained_model_field=b'services', null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.Customer', verbose_name=b'Customer'),
        ),
    ]
