# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-12 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0037_auto_20180712_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmaceuticalinventorymovements',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.Customer', verbose_name=b'Customer'),
        ),
    ]
