# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-12 16:13
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0038_auto_20180712_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmaceuticalinventorymovements',
            name='customer',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'cashdesk', chained_model_field=b'services', null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.Customer', verbose_name=b'Customer'),
        ),
        migrations.AlterField(
            model_name='pharmaceuticalinventorymovements',
            name='sign',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field=b'cashdesk', chained_model_field=b'services', on_delete=django.db.models.deletion.CASCADE, to='settings.OperatorNew', verbose_name=b'Sign'),
        ),
    ]
