# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-13 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0029_auto_20180711_1500'),
        ('tools', '0040_auto_20180712_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashmovementscustomerdetails',
            name='cashdesk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.CashDesk'),
        ),
        migrations.AddField(
            model_name='cashmovementscustomerdetails',
            name='sign',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field=b'cashdesk', chained_model_field=b'services', null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.OperatorNew', verbose_name=b'Sign'),
        ),
        migrations.AlterField(
            model_name='cashmovementscustomerdetails',
            name='customer',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field=b'cashdesk', chained_model_field=b'services', null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.Customer', verbose_name=b'Service Customer'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to=b'uploads/2018/07/13/'),
        ),
    ]
