# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-14 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0041_auto_20180713_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashmovementscustomerdetails',
            name='cashdesk',
        ),
        migrations.RemoveField(
            model_name='cashmovementscustomerdetails',
            name='sign',
        ),
        migrations.AlterField(
            model_name='cashmovementscustomerdetails',
            name='customer',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field=b'CashMovements._cashdesk', chained_model_field=b'services', null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.Customer', verbose_name=b'Service Customer'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to=b'uploads/2018/07/14/'),
        ),
    ]
