# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-16 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0042_auto_20180714_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='eventCustomer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.Customer', verbose_name=b'Customer'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='eventDescription',
            field=models.TextField(null=True, verbose_name=b'Description'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='eventEnd',
            field=models.DateTimeField(verbose_name=b'End at'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='eventStart',
            field=models.DateTimeField(verbose_name=b'Start at'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='eventTitle',
            field=models.CharField(max_length=200, verbose_name=b'Title'),
        ),
        migrations.AlterField(
            model_name='cashmovements',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text=b'(Use "." as decimal separator)', max_digits=10, verbose_name=b'Amount'),
        ),
        migrations.AlterField(
            model_name='cashmovementscustomerdetails',
            name='customer',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field=b'cashdesk', chained_model_field=b'services', null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.Customer', verbose_name=b'Service Customer'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='customer',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field=b'services', chained_model_field=b'services', null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.Customer', verbose_name=b'Customer'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='diaryType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.DiariesType', verbose_name=b'Diary Type'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.CashDesk', verbose_name=b'Service'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='text',
            field=tinymce.models.HTMLField(blank=True, verbose_name=b'Content'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to=b'uploads/2018/07/16/'),
        ),
    ]
