# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-16 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0029_auto_20180711_1500'),
        ('tools', '0043_auto_20180716_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashmovementscustomerdetails',
            name='cashdesk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.CashDesk'),
        ),
    ]
