# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-18 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0046_auto_20180717_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashmovements',
            name='sign',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field=b'cashdesk', chained_model_field=b'services', on_delete=django.db.models.deletion.CASCADE, to='settings.OperatorNew', verbose_name=b'Sign'),
        ),
        migrations.AlterField(
            model_name='cashmovements',
            name='supplier',
            field=models.CharField(max_length=500, null=True, verbose_name=b'Supplier'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to=b'uploads/2018/07/18/'),
        ),
    ]
