# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-19 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0047_auto_20180718_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashmovements',
            name='sign',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field=b'cashdesk', chained_model_field=b'services', null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.OperatorNew', verbose_name=b'Sign'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to=b'uploads/2018/07/19/'),
        ),
    ]
