# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-21 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0048_auto_20180719_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to=b'uploads/2018/07/21/'),
        ),
    ]
