# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-24 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0050_auto_20180724_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.Customer'),
        ),
    ]
