# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-24 07:30
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0051_auto_20180724_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='customer',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field=b'services', chained_model_field=b'services', null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.Customer', verbose_name=b'Customer'),
        ),
    ]
