# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-24 08:31
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0054_auto_20180724_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='sign',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field=b'services', chained_model_field=b'services', null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.OperatorNew', verbose_name=b'Sign'),
        ),
        migrations.AlterField(
            model_name='pharmaceuticalinventorymovements',
            name='sign',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field=b'cashdesk', chained_model_field=b'cashdesk', on_delete=django.db.models.deletion.CASCADE, to='settings.OperatorNew', verbose_name=b'Sign'),
        ),
    ]
