# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-24 09:53
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0055_auto_20180724_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='sign',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'services', chained_model_field=b'services', null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.OperatorNew', verbose_name=b'Sign'),
        ),
    ]
