# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-24 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0057_auto_20180724_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.Customer'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='sign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.OperatorNew', verbose_name=b'Service'),
        ),
    ]
