# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-02 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0059_auto_20180724_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashmovementscustomerdetails',
            name='cashdesk',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True, verbose_name=b'cashdesk'),
        ),
        migrations.AlterField(
            model_name='cashmovementscustomerdetails',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.Customer', verbose_name=b'Service Customer'),
        ),
        migrations.AlterField(
            model_name='cashmovementscustomerdetails',
            name='supplier',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True, verbose_name=b'Supplier'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to=b'uploads/2018/09/02/'),
        ),
    ]
