# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-02 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0060_auto_20180902_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashmovementscustomerdetails',
            name='cashdesk',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.CashDesk'),
        ),
    ]
